version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/app
    networks:
      - strapi
  cms:
    build:
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/usr/app
    networks:
      - strapi
  db:
    image: postgres:14.1-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cms
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi

networks:
  strapi:
volumes:
  db:
